# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0f2025227217414a3b8260324072cc6afd8b3fa6f29146bd7f8d72042fc78425bd939a8f62930c96f201133746190c3acc43e20936413446808dd931ae1379bc

test:
  secret_key_base: a0c8c8499804c300baf541feba7f2aa6c0961ce8bd67c937de582d74c748e8e9e729fb8119f16842db79366c8ae411486fade500ddf2fff355b74a6445b82e65

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
